ci: _

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -17,4 +17,19 @@ jobs:
         with:
           node-version: '20'
       
-      - run: node -v
+      - name: Install dependencies
+        run: |
+          if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+          elif [ -f package-lock.json ]; then npm ci; \
+          elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+          else echo "Lockfile not found." && exit 1; \
+          fi
+      
+      - name: Build Source
+        run: |
+          if [ -f yarn.lock ]; then yarn run build; \
+          elif [ -f package-lock.json ]; then npm run build; \
+          elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+          else echo "Lockfile not found." && exit 1; \
+          fi
+          
